### ISSUE TITLE
Name and Shame

### ISSUE THREAD

**Issue by martinduke** [martinduke/congestion-control-charter#3]
Bob Briscoe suggests that the WG should "name and shame" congestion controls that are not playing well with others.

**Comment by MischMetal** [comment]
I would recommend going beyond just naming and shaming the algorithms themselves but also putting under scrutiny the people who deploy these congestion control algorithms. I have two reasons for proposing this:
1. The set of deployed congestion control algorithms on the Internet is already a superset of variants that are known, published, and open source (think beyond CUBIC, BBRvX, Reno, etc.). We have already found evidence of this happening in the TCP stack [1], and I expect it to get much worse in the future with the barrier to deploying new congestion control algorithms being much lower with QUIC. 
2. There is already significant speciation in *existing* implementations of well-known congestion control algorithms with QUIC. For example, Chromium's implementation of CUBIC modifies the value of beta because it emulates two flows. While this may be a small change, it just goes to show that we can no longer rely on just analyzing the algorithms. If the motivation behind naming and shaming CCAs is to ensure a healthy congestion control landscape, we also need to keep an eye on the many implementations of these CCAs.

[1]: The Great Internet TCP Congestion Control Census: [https://www.comp.nus.edu.sg/~ayush/images/sigmetrics2020-gordon.pdf](url)

**Comment by MischMetal** [comment]
I think we also need to think hard about what is a grave enough offense for an algorithm to be named and shamed. Flow-level fairness is a good ideal goal but impractical to achieve on the Internet. The idea of fairness and deployability is already evolving [1]. How do we want to define if an algorithm is _good enough_?

[1]: Beyond Jain’s Fairness Index: Setting the Bar For The Deployment of Congestion Control Algorithms: [https://www.cs.cmu.edu//~rware/assets/pdf/ware-hotnets19.pdf](url)

**Comment by martinduke** [comment]
After reflecting on this for a good long while, it would highly unusual for the IETF to "scrutinize" people based on the compliance of their deployments.

I think there should be place at IETF/IRTF for people to study the behaviors of deployed congestion controls, including their compliance with standards and various measures of fairness with respect to other algorithms. It would be entirely appropriate to periodically publish Informational RFCs with these assessments.

That's what "name and shame" means to me.

Whether this should happen in ICCRG or here is less clear to me. My instincts say that ICCRG should have this role.
